### PR TITLE
5 feat create card

### PR DESCRIPTION
**Pull request by mfarazahmad**
Created a basic UI for the card. Didn't add any functionality yet.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
@mfarazahmad : can you move your .idea folder to .gitignore? Also, can you pull down the most recent develop branch to make sure that your file structures match what we have. I noticed App.js still lives in the root of your branch

**Comment by sipofwater** [comment]
@mfarazahmad , for this PR, can we split out the open card into a new branch for #43.  
This PR should *not get approved/merged into develop before that happens*:
(it looks great btw!)

**Comment by fia5000** [comment]
Here I go again... PLEASE STOP 

> I'm serious. Whoever _your_ Faraz Ahmad is, its not me. Please take me off this distribution list and off your repository. faraz***@gmail.com belongs to me; I dont know why this other guy is peddling that email address around.

@mfarazahmad FIX THIS!!!!!

**Comment by mfarazahmad** [comment]
@faraz My email is farazfkm@gmail.com LOL. My apologies that you are getting tagged. I've only had this mfarazahmad github account.

**Comment by faraz** [comment]
@sipofwater stop mentioning me on this repo. @mfarazahmad  is your right guy.

**Comment by ghost** [comment]
@sipofwater, @zealousAnemone, @CollinPerkins , @mfarazahmad - HI all. Un related but I think we need to be super careful and not @  the wrong Faraz.  That guy seems to be getting aggravated.

**Review by zealousAnemone — COMMENTED** [review]
Looks great to me! I see there's something we're waiting on before it's merged, but so far, so good!

**Review by ghost — APPROVED** [review]

**Pull request merged**
